version: '3.8'

services:
  db:
    image: postgres
    container_name: userapp-postgres
    environment:
      POSTGRES_USER: userapp
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: userdb
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
